version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: jsf_lab
      POSTGRES_USER: jsf_user
      POSTGRES_PASSWORD: jsf_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U jsf_user -d jsf_lab" ]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy